[package]
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2021"
name = "uri"
version = "0.4.12"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
percent-encoding = "2.1"
thiserror = "1.0"
