[package]
name = "uri"
version = "0.1.2"
authors = ["mkoctuk <mkoctuk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11"
thiserror = "1.0"